"""Add aws_accounts table

Revision ID: 0dbca7e20306
Revises: 3263dbde79a7
Create Date: 2025-08-09 17:39:30.488318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbca7e20306'
down_revision = '3263dbde79a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('iam_role_arn', sa.String(length=255), nullable=False),
    sa.Column('focus_s3_bucket_path', sa.String(length=255), nullable=False),
    sa.Column('is_connection_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iam_role_arn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aws_accounts')
    # ### end Alembic commands ###
