"""Add email verification fields to User model

Revision ID: 50335fc9b760
Revises: 9ba839de6cf8
Create Date: 2025-08-12 01:28:41.309270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50335fc9b760'
down_revision = '9ba839de6cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Adicionar campo com valor padrão para usuários existentes
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###
