"""add_focus_granular_fields_resource_id_usage_type

Revision ID: 8f19b654ead0
Revises: dc67d4adeadc
Create Date: 2025-09-04 01:54:38.573137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f19b654ead0'
down_revision = 'dc67d4adeadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('usage_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('effective_cost', sa.Numeric(precision=12, scale=6), nullable=True))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_aws_service'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_aws_service_phase2'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_charge_category'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_charge_category_phase2'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_composite_phase2'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_member_account_id'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_member_account_id_phase2'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_service_category'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_service_category_phase2'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_usage_date'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_usage_date_phase2'))
        batch_op.drop_index(batch_op.f('idx_daily_focus_costs_variation_analysis'))
        batch_op.create_index(batch_op.f('ix_daily_focus_costs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_focus_costs_usage_type'), ['usage_type'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))

    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_focus_costs_usage_type'))
        batch_op.drop_index(batch_op.f('ix_daily_focus_costs_resource_id'))
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_variation_analysis'), ['member_account_id', 'usage_date', 'charge_category', 'aws_service'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_usage_date_phase2'), [sa.literal_column('usage_date DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_usage_date'), ['usage_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_service_category_phase2'), ['service_category'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_service_category'), ['service_category'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_member_account_id_phase2'), ['member_account_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_member_account_id'), ['member_account_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_composite_phase2'), ['member_account_id', sa.literal_column('usage_date DESC'), 'charge_category', 'aws_service'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_charge_category_phase2'), ['charge_category'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_charge_category'), ['charge_category'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_aws_service_phase2'), ['aws_service'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_focus_costs_aws_service'), ['aws_service'], unique=False)
        batch_op.drop_column('effective_cost')
        batch_op.drop_column('usage_type')
        batch_op.drop_column('resource_id')

    # ### end Alembic commands ###
