"""Add user management fields (status, role, invitation_token, invitation_expires_at)

Revision ID: b01c029c8f13
Revises: b517116a6c0d
Create Date: 2025-08-16 22:25:27.896767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01c029c8f13'
down_revision = 'b517116a6c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Adicionar colunas com valores padrão para usuários existentes
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='ACTIVE'))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='ADMIN'))  # Primeiro usuário é ADMIN
        batch_op.add_column(sa.Column('invitation_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invitation_expires_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # Remover server_default após adicionar as colunas
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)
        batch_op.alter_column('role', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('invitation_expires_at')
        batch_op.drop_column('invitation_token')
        batch_op.drop_column('role')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
