"""Create project tag configuration and discovered tags tables

Revision ID: create_tag_tables
Revises: 8f19b654ead0
Create Date: 2025-09-11 23:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'create_tag_tables'
down_revision = '8f19b654ead0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tag_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('selected_tags', sa.JSON(), nullable=True),
    sa.Column('priority_order', sa.JSON(), nullable=True),
    sa.Column('project_filters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('discovered_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tag_key', sa.String(length=100), nullable=False),
    sa.Column('tag_values', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('coverage_percent', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('first_discovered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('idx_discovered_tags_org_key', 'discovered_tags', ['organization_id', 'tag_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_discovered_tags_org_key', table_name='discovered_tags')
    op.drop_table('discovered_tags')
    op.drop_table('project_tag_configs')
    # ### end Alembic commands ###
