"""Add alarms and alarm_events tables

Revision ID: e878479fa4c9
Revises: 92db5235fd22
Create Date: 2025-08-15 00:00:15.885261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e878479fa4c9'
down_revision = '92db5235fd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('time_period', sa.String(length=50), nullable=False),
    sa.Column('severity_levels', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('trigger_date', sa.Date(), nullable=False),
    sa.Column('cost_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('breached_severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarm_events_trigger_date'), ['trigger_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarm_events_trigger_date'))

    op.drop_table('alarm_events')
    op.drop_table('alarms')
    # ### end Alembic commands ###
