"""Add history_imported field to aws_accounts

Revision ID: 89811af7d432
Revises: c72e84c80f4e
Create Date: 2025-08-11 13:43:04.883122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89811af7d432'
down_revision = 'c72e84c80f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Primeiro adicionar coluna como nullable
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_imported', sa.Boolean(), nullable=True))
    
    # Atualizar registros existentes com valor padrão False
    op.execute("UPDATE aws_accounts SET history_imported = false WHERE history_imported IS NULL")
    
    # Tornar a coluna NOT NULL
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.alter_column('history_imported', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.drop_column('history_imported')

    # ### end Alembic commands ###
