"""Add monthly_budget to AWSAccount model

Revision ID: 92db5235fd22
Revises: 50335fc9b760
Create Date: 2025-08-14 23:14:35.167815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92db5235fd22'
down_revision = '50335fc9b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_budget', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.drop_column('monthly_budget')

    # ### end Alembic commands ###
