"""Add charge_category field to daily_focus_costs

Revision ID: 9ba839de6cf8
Revises: 89811af7d432
Create Date: 2025-08-11 22:02:15.453810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba839de6cf8'
down_revision = '89811af7d432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge_category', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.drop_column('charge_category')

    # ### end Alembic commands ###
