"""Add secure onboarding fields to AWSAccount (status, external_id, payer_account_id, s3_prefix)

Revision ID: a30a9ee7af14
Revises: b01c029c8f13
Create Date: 2025-08-16 22:47:05.221946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30a9ee7af14'
down_revision = 'b01c029c8f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        # Adicionar colunas com valores padrão para contas existentes
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='ACTIVE'))
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payer_account_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('s3_prefix', sa.String(length=100), nullable=True))
        batch_op.alter_column('iam_role_arn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('focus_s3_bucket_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['external_id'])

    # Remover server_default após adicionar a coluna
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('focus_s3_bucket_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('iam_role_arn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('s3_prefix')
        batch_op.drop_column('payer_account_id')
        batch_op.drop_column('external_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
