"""Add alarm_event_actions table and notification fields

Revision ID: a631b0220e90
Revises: e878479fa4c9
Create Date: 2025-08-15 00:42:33.958639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a631b0220e90'
down_revision = 'e878479fa4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_event_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_event_id'], ['alarm_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_column('notification_email')

    op.drop_table('alarm_event_actions')
    # ### end Alembic commands ###
