"""Add member_accounts table and update daily_focus_costs to reference member_accounts

Revision ID: a9127ad17b72
Revises: a631b0220e90
Create Date: 2025-08-16 20:02:45.362765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9127ad17b72'
down_revision = 'a631b0220e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aws_account_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payer_connection_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('monthly_budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payer_connection_id'], ['aws_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_accounts_aws_account_id'), ['aws_account_id'], unique=True)

    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_account_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('_unique_daily_cost_uc'), type_='unique')
        batch_op.create_unique_constraint('_unique_daily_cost_uc', ['member_account_id', 'usage_date', 'service_category', 'aws_service'])
        batch_op.drop_constraint(batch_op.f('daily_focus_costs_aws_account_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member_accounts', ['member_account_id'], ['id'])
        batch_op.drop_column('aws_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('daily_focus_costs_aws_account_id_fkey'), 'aws_accounts', ['aws_account_id'], ['id'])
        batch_op.drop_constraint('_unique_daily_cost_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_unique_daily_cost_uc'), ['aws_account_id', 'usage_date', 'service_category', 'aws_service'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('member_account_id')

    with op.batch_alter_table('member_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_accounts_aws_account_id'))

    op.drop_table('member_accounts')
    # ### end Alembic commands ###
