"""Add is_payer column to member_accounts table

Revision ID: b517116a6c0d
Revises: a9127ad17b72
Create Date: 2025-08-16 21:02:34.465422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b517116a6c0d'
down_revision = 'a9127ad17b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_accounts', schema=None) as batch_op:
        # Adicionar coluna como nullable primeiro
        batch_op.add_column(sa.Column('is_payer', sa.Boolean(), nullable=True))
    
    # Definir valor padrão para registros existentes (todos como False inicialmente)
    op.execute("UPDATE member_accounts SET is_payer = FALSE WHERE is_payer IS NULL")
    
    # Agora tornar a coluna NOT NULL
    with op.batch_alter_table('member_accounts', schema=None) as batch_op:
        batch_op.alter_column('is_payer', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_accounts', schema=None) as batch_op:
        batch_op.drop_column('is_payer')

    # ### end Alembic commands ###
