"""Add daily_focus_costs table

Revision ID: c72e84c80f4e
Revises: 0dbca7e20306
Create Date: 2025-08-09 18:03:11.357756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72e84c80f4e'
down_revision = '0dbca7e20306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_focus_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aws_account_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('service_category', sa.String(length=255), nullable=False),
    sa.Column('aws_service', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['aws_account_id'], ['aws_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_account_id', 'usage_date', 'service_category', 'aws_service', name='_unique_daily_cost_uc')
    )
    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_focus_costs_usage_date'), ['usage_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_focus_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_focus_costs_usage_date'))

    op.drop_table('daily_focus_costs')
    # ### end Alembic commands ###
